# SwiftLint Configuration for Scroll Down iOS

# Rules to enable
opt_in_rules:
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - force_unwrapping
  - implicit_return
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - ev
    - to
    - at

force_cast: error
force_try: error
force_unwrapping: error

# Paths to exclude from linting
excluded:
  - Carthage
  - Pods
  - .build
  - build
  - DerivedData
  - ScrollDown.xcodeproj
  - ScrollDown/Tests

# Paths to include
included:
  - ScrollDown/Sources

# Custom rules
custom_rules:
  no_direct_date_init:
    name: "No Direct Date Init"
    regex: 'Date\(\)'
    message: "Use AppDate.now() instead of Date() for testability"
    severity: warning
    
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\('
    message: "Use Logger instead of print() for production code"
    severity: warning
